---
title: "Data Manipulation"
output: github_document
---

```{r setup}
library(tidyverse)
```

## Load in the FAS Litters Data

```{r}
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```

## `select`

Choose some columns and not others.

```{r}
select(litters_df, group, gd0_weight)   #keep only these columns
```

```{r}
select(litters_df, group, gd0_weight:gd_of_birth)
```

```{r}
select(litters_df, -litter_number)  #what we want to lose
```

Renaming columns ...

```{r}
select(litters_df, GROUP = group, LITTer_NUmBer = litter_number)
```

```{r}
rename(litters_df, GROUP = group, LITTer_NUmBer = litter_number) #keep other column and rename the specific ones
```

Select helpers 

```{r}
select(litters_df, starts_with("gd")) #only show data with keywords
```

```{r}
select(litters_df, litter_number, everything())
```

```{r}
relocate(litters_df, litter_number)
```

## `filter`

```{r}
filter(litters_df, gd0_weight < 22)
```

```{r}
filter(litters_df, gd0_weight >= 22)
```

```{r}
filter(litters_df, gd_of_birth == 20)  # == a test for equality
```

```{r}
filter(litters_df, !(gd_of_birth == 20))  #give not equal to 20, everything that's not the case
```

```{r}
filter(litters_df, gd0_weight >= 22, gd_of_birth == 20)
```

```{r}
filter(litters_df, group == "Mod8")
```

```{r}
filter(litters_df, group %in% c("Con7", "Mod8")) #either this two options
```








